version: '2'
services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.docker
        volumes:
            - ./data/nginx/certs:/etc/letsencrypt
            - ./data/nginx/certs-data:/data/letsencrypt
        ports:
            - 80:80
            - 443:443
        links:
            - server

    server:
        build:
            context: .
            dockerfile: docker/server.docker
        ports:
            - 3000:3000
